# Generated by Django 3.1.4 on 2021-01-22 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alltask',
            name='id',
        ),
        migrations.AddField(
            model_name='alltask',
            name='task_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alltask',
            name='about',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='alltask',
            name='subDateTime',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='alltask',
            name='taskName',
            field=models.CharField(max_length=30),
        ),
    ]
