# Generated by Django 3.1.4 on 2021-01-22 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210123_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alltask',
            name='task_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
