# Generated by Django 3.1.4 on 2021-01-22 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210123_0012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alltask',
            name='task_id',
        ),
        migrations.AddField(
            model_name='alltask',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
