# Generated by Django 3.1.4 on 2021-01-22 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210123_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alltask',
            name='subDateTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
