# Generated by Django 3.1.4 on 2021-01-22 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210123_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='alltask',
            name='slug',
            field=models.CharField(default='GET', max_length=80),
            preserve_default=False,
        ),
    ]
