# Generated by Django 3.1.4 on 2021-01-29 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alltask_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='alltask',
            name='sColor',
            field=models.CharField(default='primary', max_length=10),
            preserve_default=False,
        ),
    ]
